
language: php

php:
  - '7.0'
  - '7.2'

git:
  depth: 10
  submodules: false

env:
  global:
    - BUILD_LEADER_ID=1

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

install:
  - git submodule update --init --jobs 9
  - composer install --prefer-dist --no-interaction
script:
  - vendor/bin/phpcs -n
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_script:
  - bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - stage: test
      os: osx
      osx_image: xcode9.1
      language: generic
      before_install:
        # Fix ruby error https://github.com/Homebrew/brew/issues/3299
        - brew update
        - brew tap homebrew/homebrew-php
        - brew install php71
        - brew install homebrew/php/php71-xdebug
        - curl https://getcomposer.org/installer | php
        - ln -s "`pwd`/composer.phar" /usr/local/bin/composer
    - stage: release
      language: node_js
      node_js: '8'
      services:
        - docker
      before_install:
        - git config --replace-all remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
        - git fetch --tags
      install:
        - npm install
      script:
        - npm run semantic-release

stages:
  - test
  - name: release
    if: branch = master

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
